"""Initial migration

Revision ID: 036c0cc04463
Revises: c847a2a9d9b7
Create Date: 2025-04-18 17:02:01.735618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036c0cc04463'
down_revision = 'c847a2a9d9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('card_set',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=150), nullable=False),
    # sa.Column('year', sa.Integer(), nullable=False),
    # sa.Column('manufacturer', sa.String(length=100), nullable=True),
    # sa.Column('sport', sa.String(length=50), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('card_set', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_card_set_name'), ['name'], unique=True)
    #     batch_op.create_index(batch_op.f('ix_card_set_year'), ['year'], unique=False)

    # op.create_table('player',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('full_name', sa.String(length=150), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('player', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_player_full_name'), ['full_name'], unique=True)

    # op.create_table('team',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=100), nullable=False),
    # sa.Column('abbreviation', sa.String(length=10), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('team', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_team_abbreviation'), ['abbreviation'], unique=True)
    #     batch_op.create_index(batch_op.f('ix_team_name'), ['name'], unique=True)

    # op.create_table('user',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('username', sa.String(length=64), nullable=False),
    # sa.Column('email', sa.String(length=120), nullable=False),
    # sa.Column('password_hash', sa.String(length=256), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
    #     batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # op.create_table('card',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('player_name', sa.String(length=100), nullable=False),
    # sa.Column('card_year', sa.Integer(), nullable=False),
    # sa.Column('manufacturer', sa.String(length=100), nullable=False),
    # sa.Column('card_number', sa.String(length=50), nullable=True),
    # sa.Column('team', sa.String(length=100), nullable=True),
    # sa.Column('grade', sa.String(length=50), nullable=True),
    # sa.Column('image_url', sa.String(length=500), nullable=True),
    # sa.Column('notes', sa.Text(), nullable=True),
    # sa.Column('sport', sa.String(length=50), nullable=True),
    # sa.Column('owner_id', sa.Integer(), nullable=False),
    # sa.Column('date_added', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    pass # Add pass if all operations are commented out
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_name'))
        batch_op.drop_index(batch_op.f('ix_team_abbreviation'))

    op.drop_table('team')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_full_name'))

    op.drop_table('player')
    with op.batch_alter_table('card_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_set_year'))
        batch_op.drop_index(batch_op.f('ix_card_set_name'))

    op.drop_table('card_set')
    # ### end Alembic commands ###
