"""Add fields to Card model

Revision ID: 22c82713753b
Revises: 794248b5dd3c
Create Date: 2025-04-09 22:42:29.171163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c82713753b'
down_revision = '794248b5dd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_set', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_card_card_set'), ['card_set'], unique=False)
        batch_op.drop_constraint('fk_card_card_set', type_='foreignkey')
        batch_op.drop_column('card_set_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_set_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_card_card_set', 'card_set', ['card_set_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_card_card_set'))
        batch_op.drop_column('card_set')

    # ### end Alembic commands ###
