"""Add card_set_id to Card model

Revision ID: 794248b5dd3c
Revises: 55aa5cc0eb70
Create Date: 2025-04-09 20:11:25.615015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794248b5dd3c'
down_revision = '55aa5cc0eb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('sport', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_set_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_card_set_year'), ['year'], unique=False)

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_set_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_card_card_set')
        batch_op.create_foreign_key(None, 'card_set', ['card_set_id'], ['id'])
        batch_op.drop_column('card_set')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_set', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_card_card_set', ['card_set'], unique=False)
        batch_op.drop_column('card_set_id')

    with op.batch_alter_table('card_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_set_year'))
        batch_op.drop_index(batch_op.f('ix_card_set_name'))

    op.drop_table('card_set')
    # ### end Alembic commands ###
