"""Add sport column to card table (attempt 2)

Revision ID: 8f1b8b423eff
Revises: 22c82713753b
Create Date: 2025-04-10 10:58:45.461065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1b8b423eff'
down_revision = '22c82713753b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport', sa.String(length=50), nullable=True))
        batch_op.alter_column('card_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=7),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('card_year',
               existing_type=sa.String(length=7),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('sport')

    # ### end Alembic commands ###
