"""Replace card_set with manufacturer

Revision ID: c847a2a9d9b7
Revises: 8f1b8b423eff
Create Date: 2025-04-10 11:34:51.116036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c847a2a9d9b7'
down_revision = '8f1b8b423eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=128), nullable=True))
        batch_op.drop_index('ix_card_card_set')
        batch_op.create_index(batch_op.f('ix_card_manufacturer'), ['manufacturer'], unique=False)
        batch_op.drop_column('card_set')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_set', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_index(batch_op.f('ix_card_manufacturer'))
        batch_op.create_index('ix_card_card_set', ['card_set'], unique=False)
        batch_op.drop_column('manufacturer')

    # ### end Alembic commands ###
